### ISSUE TITLE
Set up logging

### ISSUE THREAD

**Issue by bevzzz** [bevzzz/bouncer#3]
## Context
Clear logs will make my life easier, I should add that to my project

## Goal
Have a simple logging function, like printDebug and a file (just 1 for now) where all the logs should be written.

## Tasks
- [x] create a printDebug-like function, date format `%d-%m-%Y %H:%M:%S`
- [ ] set up a log-file

## Definition of Done
- [ ] Tested
- [ ] Merged to DEV

**Comment by bevzzz** [comment]
`printDebug` is available in **helpers** module  
currently only produces .debug-level statements  
  
would be nice to figure out a way to import it without any prefix (h.printDebug)
