### ISSUE TITLE
Run the app from Docker

### ISSUE THREAD

**Issue by bevzzz** [bevzzz/bouncer#5]
### Context
I want to be able to run my app from a Docker container.
https://docs.docker.com/compose/

### Tasks
- [x]  Get familiar with docker-compose and install all the necessary elements infrastructure
- [x] Create a DockerHub repository
- [x] Build a container and deploy the app locally
- [ ] Deploy from Raspberry Pi

### Acceptance criteria
- `Dockerfile` and `docker-compose.yml` are added to the repository
- The app is running on the server

**Comment by bevzzz** [comment]
running from a single docker container with persistence on local directory
pretty happy about it
will return to docker-compose when the facial recognition service is ready
